title: Amundsen by Lyft
description: Open source data discovery and metadata engine.
baseurl: "/amundsen" # the subpath of your site, e.g. /blog
url: "https://kylewaynebenson.github.io/amundsen" # the base hostname & protocol for your site, e.g. http://example.com

#Links within the site
documentation: "https://lyft.github.io/amundsen/"
getstarted: "https://github.com/lyft/amundsen"

destination: dist

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
